version: 2

registries:
  maven-google:
    type: maven-repository
    url: "https://dl.google.com/dl/android/maven2/"

  maven-central:
    type: maven-repository
    url: "https://repo.maven.apache.org/maven2"

  jitpack:
    type: maven-repository
    url: "https://www.jitpack.io"

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - maven-central
      - maven-google
      - jitpack
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      - dependency-name: "org.fossify:commons"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
