[versions]
#jetbrains
kotlin = "2.2.21"
#KSP
ksp = "2.3.2"
#Detekt
detekt = "1.23.8"
detektCompose = "0.4.27"
#AndroidX
androidx-print = "1.1.0"
androidx-swiperefreshlayout = "1.1.0"
androidx-constraintlayout = "2.2.1"
androidx-documentfile = "1.1.0"
#exif
exif = "1.0.1"
#Room
room = "2.8.3"
#Fossify
commons = "5.7.3"
#Gradle4
gradlePlugins-agp = "8.11.1"
#Other
androidGifDrawable = "1.2.29"
androidImageCropper = "4.6.0"
animationAndroid = "3.0.5"
glideCompiler = "5.0.5"
zjupureWebpdecoder = "2.7.4.16.0"
jxlDecoder = "2.5.2"
gestureviews = "e706487a14"
androidsvgAar = "1.4"
androidphotofilters = "193f2ae509"
sanselan = "0.97-incubator"
media3Exoplayer = "1.8.0"
okhttp = "5.3.1"
okio = "3.16.3"
picasso = "2.71828"
subsamplingScaleImageView = "d705c3c4ad"
#build
app-build-compileSDKVersion = "36"
app-build-targetSDK = "36"
app-build-minimumSDK = "26"
app-build-javaVersion = "VERSION_17"
app-build-kotlinJVMTarget = "17"
[libraries]
#AndroidX
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-print = { module = "androidx.print:print", version.ref = "androidx-print" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "androidx-documentfile" }
#exif
exif = { module = "it.sephiroth.android.exif:library", version.ref = "exif" }
#Room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
#Compose
compose-detekt = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektCompose" }
#Fossify
fossify-commons = { module = "org.fossify:commons", version.ref = "commons" }
#Other
android-gif-drawable = { module = "pl.droidsonroids.gif:android-gif-drawable", version.ref = "androidGifDrawable" }
android-image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "androidImageCropper" }
subsamplingscaleimageview = { module = "org.fossify:subsampling-scale-image-view", version.ref = "subsamplingScaleImageView" }
androidsvg-aar = { module = "com.caverock:androidsvg-aar", version.ref = "androidsvgAar" }
gestureviews = { module = "org.fossify:gestureviews", version.ref = "gestureviews" }
androidphotofilters = { module = "com.github.naveensingh:androidphotofilters", version.ref = "androidphotofilters" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
sanselan = { module = "org.apache.sanselan:sanselan", version.ref = "sanselan" }
apng = { module = "com.github.penfeizhou.android.animation:apng", version.ref = "animationAndroid" }
awebp = { module = "com.github.penfeizhou.android.animation:awebp", version.ref = "animationAndroid" }
avif = { module = "com.github.penfeizhou.android.animation:avif", version.ref = "animationAndroid" }
glide-compiler = { module = "com.github.bumptech.glide:ksp", version.ref = "glideCompiler" }
zjupure-webpdecoder = { module = "com.github.zjupure:webpdecoder", version.ref = "zjupureWebpdecoder" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
avif-integration = { group = "com.github.bumptech.glide", name = "avif-integration", version.ref = "glideCompiler" }
jxl-integration = { group = "io.github.awxkee", name = "jxl-coder-glide", version.ref = "jxlDecoder" }
[bundles]
room = [
    "androidx-room-ktx",
    "androidx-room-runtime",
]
[plugins]
android = { id = "com.android.application", version.ref = "gradlePlugins-agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
