name: PR

on:
    pull_request:
        branches: [main]
        paths-ignore:
            - ".github/**"
            - "CHANGELOG.md"
            - "docs/**"
            - "fastlane/**"
            - "LICENSE"
            - "README.md"

jobs:
    call-pr-workflow:
        uses: FossifyOrg/.github/.github/workflows/pr.yml@main
        with:
            test_task: ":app:testFossDebugUnitTest"
