name: Testing build (on PR)

on:
    pull_request:
        branches: [main]
        types: [labeled, opened, synchronize, reopened]
        paths-ignore:
            - ".github/**"
            - "CHANGELOG.md"
            - "docs/**"
            - "fastlane/**"
            - "LICENSE"
            - "README.md"

jobs:
    call-testing-build-workflow:
        uses: FossifyOrg/.github/.github/workflows/testing-build.yml@main
        secrets: inherit
