name: Update Fossify Commons

on:
  repository_dispatch:
    types: [update-commons]
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 0"

jobs:
  update-commons:
    uses: FossifyOrg/.github/.github/workflows/update-commons.yml@main
    secrets: inherit
